let pokemonArray=[
    {name:'Mewtwo', type:'Psychic', id:150, randomFact: "Mewtwo is a genetically modified Pokemon created with Mew's DNA. Its only purpose is to battle"},
    {name:'Rayquaza', type:['Dragon','Flying'], id:384, randomFact:"Rayquaza is often called the 'Sk High Pokemon' due to its habitat being high in the O-Zone Layer!"},
    {name:'Lugia', type: ['Psychic','Flying'], id:249, randomFact:"Lugia is know as the guardian of the seas. It sleeps in a deep ocean trench and only comes up to calm storms!"},
    {name:'Darkrai', type:'Dark', id:491, randomFact: 'Darkrai pokemon can be found on the Newmoon Island, or Clamberclaw Cliffs'},
    {name:'Dialga', type:'Steel', id:483, randomFact: 'The average Dialga weighs 1505.8 lbs!'},
    {name:'Ho-Oh', type:['Fire','Flying'], id:250, randomFact: "Leagend has it, the Ho-Oh's body glows seven different colors as it flies!"},
    {name:'Groudon', type:'Ground', id:383, randomFact:'Groudon and Kyogre fought in many epic battles, both in the pursuit of gaining the power of nature.'},
    {name:'Genesect', type:['Bug','Steel'], id:649, randomFact: "Genesect Pokemon have been around for 300 million years!"},
    {name:'Celebi', type:['Psychic','Grass'], id:251, randomFact:"Celebi can travel through time to find beautiful forrests to make it's home"},
    {name:'Gengar', type:['Ghost', 'Poison'], id:94, randomFact:"This pokemon will hide in the shaddows of it's foes, waiting for the perfect time to stike!"},
    {name:'Zekrom', type:['Dragon','Electric'], id:644, randomFact:"Zekrom has a generator in its tail that generate electricity to use against those who want to destroy the world"},
    {name:'Heatran', type:''},
    {name:'Zapdos', type:''},
    {name:'Chansey', type:''},
    {name:'Jirachi', type:['Steel', 'Flying'], id:385, randomFact:"Jirachi can sense danger and defend it's self, all while sleeping!"},
    {name:'Feebas', type:''},
    {name:'Hydreigon', type:''},
    {name:'Arceus', type:''},
    {name:'Kyogre', type:''},
    {name:'Kyurem', type:''},
    {name:'Landorus', type:['Ground','Flying'], id:645, randomFact:"Landorus is called the 'Abundance Pokemon' because the lands that are visited by them are blessed with bountiful crops and increased soil nutrients"},
    {name:'Cresselia', type:''},
    {name:'Lucario', type:''},
    {name:'Dragonite', type:''},
    {name:'Gyrados', type:''},
    {name:'JigglyPuff', type:''},
    {name:'Cosmoem', type:''},
    {name:'Tornadus', type:''},
    {name:'Necrozma', type:''},
    {name:'Kyurem', type:['Dragon', 'Ice'], id:646, randomFact: "The extreme cold of this pokemon's body keeps it from being able to harness it's emense power"},
    {name:'Tapu Koko', type:['Electric','Fairy'], id:785, randomFact:"Tapu Koko is the guardian diety of Melemele"},
    {name:'Regieleki', type:'Electric'}]